"""empty message

Revision ID: 845cb5bc5e9d
Revises: 1422edceb256
Create Date: 2017-07-27 12:48:37.403683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5d74bcbaba8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('sleeprecords',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=True),
                    sa.Column('sleepState', sa.String(length=60), nullable=True),
                    sa.Column('startTime', sa.BIGINT, nullable=True),
                    sa.Column('endTime', sa.BIGINT, nullable=True),
                    sa.Column('fullTimeSlept', sa.Integer(), nullable=True),
                    sa.Column('date', sa.BIGINT(), nullable=True),
                    sa.Column('timeToSleep', sa.Integer(), nullable=True),
                    sa.Column('timeWokenUp', sa.Integer(), nullable=True),
                    sa.Column('durationWokenUp', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleeprecords')
    op.drop_table('users')
    # ### end Alembic commands ###